package org.metadatacenter.artifacts.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.metadatacenter.artifacts.model.core.TemplateSchemaArtifact;
import org.metadatacenter.artifacts.model.reader.JsonArtifactReader;
import org.metadatacenter.artifacts.model.reader.YamlArtifactReader;
import org.metadatacenter.artifacts.model.renderer.JsonArtifactRenderer;
import org.metadatacenter.artifacts.model.renderer.YamlArtifactRenderer;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.LinkedHashMap;

/**
 * One-shot regeneration utility for the golden JSON Schema fixtures under
 * {@code src/test/resources/templates-json/}.
 *
 * <p>Sister utility to {@link GoldenYamlGenerator}. Real-world CEDAR JSON Schemas
 * shipped by older toolchains typically contain drift from current canonical CEDAR
 * output — lowercased title boilerplate, older "generated by" descriptions, a
 * different shape for {@code @context.required}, empty-string entries in
 * {@code _ui.propertyDescriptions}, and so on. This utility normalizes each input
 * by round-tripping it through the artifact library's reader/renderer in
 * <em>both</em> directions:
 *
 * <pre>{@code
 *   JsonArtifactReader.readTemplateSchemaArtifact
 *     -> YamlArtifactRenderer.renderTemplateSchemaArtifact (drops internalName/description)
 *     -> YamlArtifactReader.readTemplateSchemaArtifact     (rebuilds defaults via builder)
 *     -> JsonArtifactRenderer.renderTemplateSchemaArtifact
 *     -> Jackson pretty-print
 * }</pre>
 *
 * <p>The YAML round-trip in the middle is intentional: it forces the goldens to
 * be byte-stable under {@link TemplateBatteryJsonRoundTripTest}'s JSON &rarr;
 * YAML &rarr; JSON pipeline. Without it, fields that only the JSON renderer
 * preserves (e.g. {@code internalName}, {@code internalDescription}) would
 * appear stable on a JSON &rarr; JSON round-trip but drift on a full circle.
 *
 * <p>Not a unit test (no {@code @Test} methods). Run with:
 *
 * <pre>{@code
 *   mvn test-compile exec:java \
 *       -Dexec.classpathScope=test \
 *       -Dexec.mainClass=org.metadatacenter.artifacts.model.GoldenJsonGenerator \
 *       -Dexec.args="/path/to/source-json-dir src/test/resources/templates-json"
 * }</pre>
 */
public final class GoldenJsonGenerator
{
  private GoldenJsonGenerator() {}

  public static void main(String[] args) throws IOException
  {
    if (args.length != 2) {
      System.err.println("usage: GoldenJsonGenerator <input-dir-with-json> <output-dir-for-json>");
      System.exit(1);
    }
    Path inDir = Paths.get(args[0]);
    Path outDir = Paths.get(args[1]);
    if (!Files.isDirectory(inDir))
      throw new IllegalArgumentException("input dir does not exist: " + inDir);
    Files.createDirectories(outDir);

    ObjectMapper jackson = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    JsonArtifactReader jsonReader = new JsonArtifactReader();
    YamlArtifactRenderer yamlRenderer = new YamlArtifactRenderer(false);
    YamlArtifactReader yamlReader = new YamlArtifactReader();
    JsonArtifactRenderer jsonRenderer = new JsonArtifactRenderer();

    int ok = 0;
    int fail = 0;
    try (DirectoryStream<Path> ds = Files.newDirectoryStream(inDir, "*.json")) {
      for (Path jsonFile : ds) {
        String stem = jsonFile.getFileName().toString();
        stem = stem.substring(0, stem.length() - ".json".length());
        Path outFile = outDir.resolve(stem + ".json");
        try {
          ObjectNode original = (ObjectNode) jackson.readTree(Files.newBufferedReader(jsonFile));
          // JSON -> model -> YAML -> model -> JSON. The YAML hop forces the model
          // to drop and then regenerate fields (internalName / internalDescription)
          // that only the JSON serialization carries, so the resulting JSON is
          // byte-stable under TemplateBatteryJsonRoundTripTest's pipeline.
          TemplateSchemaArtifact fromJson = jsonReader.readTemplateSchemaArtifact(original);
          LinkedHashMap<String, Object> yamlMap = yamlRenderer.renderTemplateSchemaArtifact(fromJson);
          TemplateSchemaArtifact fromYaml = yamlReader.readTemplateSchemaArtifact(yamlMap);
          ObjectNode regenerated = jsonRenderer.renderTemplateSchemaArtifact(fromYaml);
          Files.writeString(outFile, jackson.writeValueAsString(regenerated), StandardCharsets.UTF_8);
          System.out.println("ok  " + stem);
          ok++;
        } catch (Exception e) {
          System.err.println("FAIL " + stem + " -- " + e.getClass().getSimpleName() + ": " + e.getMessage());
          fail++;
        }
      }
    }
    System.out.println();
    System.out.println("Generated " + ok + " golden JSON files; " + fail + " failures.");
    if (fail > 0) System.exit(2);
  }
}
