package org.metadatacenter.artifacts.model;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.metadatacenter.artifacts.model.core.TemplateSchemaArtifact;
import org.metadatacenter.artifacts.model.reader.JsonArtifactReader;
import org.metadatacenter.artifacts.model.reader.YamlArtifactReader;
import org.metadatacenter.artifacts.model.renderer.JsonArtifactRenderer;
import org.metadatacenter.artifacts.model.renderer.YamlArtifactRenderer;

import java.net.URL;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Full-circle stress test from the JSON Schema side: for every {@code *.json}
 * fixture under {@code src/test/resources/hubmap-golden-json/}, runs the round trip
 *
 * <pre>{@code
 *   originalJsonSchema
 *     -> JsonArtifactReader   -> TemplateSchemaArtifact
 *     -> YamlArtifactRenderer -> LinkedHashMap (YAML form)
 *     -> YamlArtifactReader   -> TemplateSchemaArtifact
 *     -> JsonArtifactRenderer -> regeneratedJsonSchema
 * }</pre>
 *
 * and asserts that {@code originalJsonSchema} and {@code regeneratedJsonSchema} are
 * structurally equal. This is the mirror of {@link HubmapTemplatesFullRoundTripTest},
 * which starts from YAML; this one starts from JSON.
 *
 * <p>The fixtures are <em>not</em> the original HuBMAP JSON Schemas — those were
 * generated by an older toolchain (CEDAR Template Editor 2.7.1) and contained
 * drift from current canonical CEDAR output (lowercased title boilerplate,
 * older "generated by" descriptions, a different shape for
 * {@code @context.required}, and empty-string entries in
 * {@code _ui.propertyDescriptions}). The fixtures here are produced by
 * {@link GoldenJsonGenerator}, which normalizes each original by round-tripping
 * it through the library's own reader and renderer — yielding the form the
 * current library considers canonical.
 *
 * <p>A failure here means either the JSON reader didn't preserve some field, the
 * YAML renderer dropped it, the YAML reader didn't reconstruct it, or the JSON
 * renderer emitted something different. The diff identifies the field; the test
 * name identifies the template.
 */
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class HubmapTemplatesJsonRoundTripTest
{
  private static final String FIXTURES_RESOURCE = "hubmap-golden-json";

  private JsonArtifactReader jsonReader;
  private YamlArtifactRenderer yamlRenderer;
  private YamlArtifactReader yamlReader;
  private JsonArtifactRenderer jsonRenderer;
  private ObjectMapper jackson;

  private final List<String> passes = new ArrayList<>();
  private final List<String> failures = new ArrayList<>();

  @BeforeEach
  public void setUp()
  {
    jsonReader = new JsonArtifactReader();
    yamlRenderer = new YamlArtifactRenderer(false);
    yamlReader = new YamlArtifactReader();
    jsonRenderer = new JsonArtifactRenderer();
    jackson = new ObjectMapper();
  }

  @BeforeAll
  public void announceBattery()
  {
    System.out.println("[HubmapTemplatesJsonRoundTripTest] running against "
      + "src/test/resources/" + FIXTURES_RESOURCE + "/");
  }

  @AfterAll
  public void printSummary()
  {
    int total = passes.size() + failures.size();
    System.out.println("[HubmapTemplatesJsonRoundTripTest] summary: "
      + passes.size() + "/" + total + " templates round-tripped structurally");
    if (!failures.isEmpty()) {
      System.out.println("[HubmapTemplatesJsonRoundTripTest] failures:");
      for (String f : failures)
        System.out.println("  - " + f);
    }
  }

  @ParameterizedTest(name = "{0}")
  @MethodSource("templates")
  public void roundTripJsonSchemaThroughYamlAndBackStructurallyEqual(String displayName, Path jsonFile) throws Exception
  {
    ObjectNode originalJson = (ObjectNode) jackson.readTree(jsonFile.toFile());

    TemplateSchemaArtifact fromJson;
    try {
      fromJson = jsonReader.readTemplateSchemaArtifact(originalJson);
    } catch (Exception e) {
      failures.add(displayName + " — JsonArtifactReader rejected original JSON: " + e.getMessage());
      throw e;
    }

    LinkedHashMap<String, Object> yamlMap = yamlRenderer.renderTemplateSchemaArtifact(fromJson);

    TemplateSchemaArtifact fromYaml;
    try {
      fromYaml = yamlReader.readTemplateSchemaArtifact(yamlMap);
    } catch (Exception e) {
      failures.add(displayName + " — YamlArtifactReader rejected the rendered YAML: " + e.getMessage());
      throw e;
    }

    ObjectNode regeneratedJson = jsonRenderer.renderTemplateSchemaArtifact(fromYaml);

    // Convert both JsonNode trees to Map / List / scalar form so we can reuse the
    // tree-walk diff. Jackson's convertValue handles the conversion uniformly.
    @SuppressWarnings("unchecked")
    Map<String, Object> originalMap = jackson.convertValue(originalJson, Map.class);
    @SuppressWarnings("unchecked")
    Map<String, Object> regeneratedMap = jackson.convertValue(regeneratedJson, Map.class);

    String diff = describeFirstDifference("", originalMap, regeneratedMap);
    if (diff != null) {
      failures.add(displayName + " — structural diff: " + diff);
      fail("JSON Schema round-trip for " + jsonFile.getFileName() + " is not structurally equal.\n"
        + "First difference: " + diff);
    }

    passes.add(displayName);
  }

  // -----------------------------------------------------------------------
  // argument source
  // -----------------------------------------------------------------------

  public Stream<Arguments> templates() throws Exception
  {
    URL resource = getClass().getClassLoader().getResource(FIXTURES_RESOURCE);
    assertNotNull(resource, "fixtures folder not on classpath: src/test/resources/" + FIXTURES_RESOURCE);
    Path dir = Paths.get(resource.toURI());
    assertTrue(Files.isDirectory(dir), "fixtures path is not a directory: " + dir);

    List<Arguments> args = new ArrayList<>();
    try (DirectoryStream<Path> ds = Files.newDirectoryStream(dir, "*.json")) {
      for (Path json : ds) {
        String stem = json.getFileName().toString();
        String displayName = stem.substring(0, stem.length() - ".json".length());
        args.add(Arguments.of(displayName, json));
      }
    }
    args.sort((a, b) -> ((String) a.get()[0]).compareTo((String) b.get()[0]));
    return args.stream();
  }

  // -----------------------------------------------------------------------
  // diff helper — same shape as HubmapTemplatesFullRoundTripTest. Number subtypes
  // compare by numeric value.
  // -----------------------------------------------------------------------

  @SuppressWarnings("unchecked")
  private static String describeFirstDifference(String path, Object a, Object b)
  {
    if (a == null && b == null) return null;
    if (a == null) return path + " (missing in original; regenerated has: " + summarize(b) + ")";
    if (b == null) return path + " (missing in regenerated; original had: " + summarize(a) + ")";

    if (a instanceof Map<?, ?> && b instanceof Map<?, ?>) {
      Map<String, Object> ma = (Map<String, Object>) a;
      Map<String, Object> mb = (Map<String, Object>) b;
      for (String key : ma.keySet()) {
        if (!mb.containsKey(key))
          return path + "/" + key + " (key in original, missing in regenerated; original value: "
            + summarize(ma.get(key)) + ")";
        String childDiff = describeFirstDifference(path + "/" + key, ma.get(key), mb.get(key));
        if (childDiff != null) return childDiff;
      }
      for (String key : mb.keySet()) {
        if (!ma.containsKey(key))
          return path + "/" + key + " (key in regenerated, missing in original; regenerated value: "
            + summarize(mb.get(key)) + ")";
      }
      return null;
    }

    if (a instanceof List<?> && b instanceof List<?>) {
      List<Object> la = (List<Object>) a;
      List<Object> lb = (List<Object>) b;
      if (la.size() != lb.size())
        return path + " (list size differs: original=" + la.size() + ", regenerated=" + lb.size() + ")";
      for (int i = 0; i < la.size(); i++) {
        String childDiff = describeFirstDifference(path + "[" + i + "]", la.get(i), lb.get(i));
        if (childDiff != null) return childDiff;
      }
      return null;
    }

    if (a instanceof Number && b instanceof Number) {
      if (Double.compare(((Number) a).doubleValue(), ((Number) b).doubleValue()) == 0)
        return null;
    }
    if (!a.equals(b))
      return path + " (value differs: original=" + summarize(a) + " <" + a.getClass().getSimpleName()
        + ">, regenerated=" + summarize(b) + " <" + b.getClass().getSimpleName() + ">)";
    return null;
  }

  private static String summarize(Object v)
  {
    if (v == null) return "null";
    String s = String.valueOf(v);
    return s.length() <= 200 ? s : s.substring(0, 200) + "...";
  }
}
