package org.metadatacenter.artifacts.model.renderer;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import org.metadatacenter.artifacts.model.core.Artifact;
import org.metadatacenter.artifacts.model.core.ChildSchemaArtifact;
import org.metadatacenter.artifacts.model.core.ElementSchemaArtifact;
import org.metadatacenter.artifacts.model.core.FieldSchemaArtifact;
import org.metadatacenter.artifacts.model.core.MonitoredArtifact;
import org.metadatacenter.artifacts.model.core.ParentSchemaArtifact;
import org.metadatacenter.artifacts.model.core.SchemaArtifact;
import org.metadatacenter.artifacts.model.core.TemplateInstanceArtifact;
import org.metadatacenter.artifacts.model.core.TemplateSchemaArtifact;
import org.metadatacenter.model.ModelNodeNames;

import java.net.URI;
import java.util.Map;

import static org.metadatacenter.model.ModelNodeNames.BIBO;
import static org.metadatacenter.model.ModelNodeNames.BIBO_STATUS;
import static org.metadatacenter.model.ModelNodeNames.JSON_LD_CONTEXT;
import static org.metadatacenter.model.ModelNodeNames.JSON_LD_ID;
import static org.metadatacenter.model.ModelNodeNames.JSON_LD_TYPE;
import static org.metadatacenter.model.ModelNodeNames.JSON_LD_VALUE;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_ADDITIONAL_PROPERTIES;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_DESCRIPTION;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_FORMAT;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_MIN_LENGTH;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_OBJECT;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_PROPERTIES;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_REQUIRED;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_SCHEMA;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_TITLE;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_TYPE;
import static org.metadatacenter.model.ModelNodeNames.OSLC;
import static org.metadatacenter.model.ModelNodeNames.OSLC_MODIFIED_BY;
import static org.metadatacenter.model.ModelNodeNames.PAV;
import static org.metadatacenter.model.ModelNodeNames.PAV_CREATED_BY;
import static org.metadatacenter.model.ModelNodeNames.PAV_CREATED_ON;
import static org.metadatacenter.model.ModelNodeNames.PAV_DERIVED_FROM;
import static org.metadatacenter.model.ModelNodeNames.PAV_LAST_UPDATED_ON;
import static org.metadatacenter.model.ModelNodeNames.PAV_PREVIOUS_VERSION;
import static org.metadatacenter.model.ModelNodeNames.PAV_VERSION;
import static org.metadatacenter.model.ModelNodeNames.RDFS;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_IS_BASED_ON;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_DESCRIPTION;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_IDENTIFIER;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_NAME;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_SCHEMA_VERSION;
import static org.metadatacenter.model.ModelNodeNames.SKOS;
import static org.metadatacenter.model.ModelNodeNames.SKOS_ALTLABEL;
import static org.metadatacenter.model.ModelNodeNames.SKOS_PREFLABEL;
import static org.metadatacenter.model.ModelNodeNames.UI;
import static org.metadatacenter.model.ModelNodeNames.VALUE_CONSTRAINTS;
import static org.metadatacenter.model.ModelNodeNames.XSD;
import static org.metadatacenter.model.ModelNodeValues.BIBO_IRI;
import static org.metadatacenter.model.ModelNodeValues.OSLC_IRI;
import static org.metadatacenter.model.ModelNodeValues.PAV_IRI;
import static org.metadatacenter.model.ModelNodeValues.RDFS_IRI;
import static org.metadatacenter.model.ModelNodeValues.SCHEMA_IRI;
import static org.metadatacenter.model.ModelNodeValues.SKOS_IRI;
import static org.metadatacenter.model.ModelNodeValues.XSD_IRI;

public class ArtifactRenderer
{
  private final ObjectMapper mapper;

  public ArtifactRenderer()
  {
    this.mapper = new ObjectMapper();
    mapper.registerModule(new Jdk8Module());
    mapper.setSerializationInclusion(JsonInclude.Include.NON_ABSENT);
  }

  /**
   * Generate a JSON Schema specification for a template schema artifact
   * <p></p>
   * An example artifact specification could look as follows:
   * <pre>
   * {
   *   "$schema": "http://json-schema.org/draft-04/schema#",
   *   "valueType": "object",
   *   "title": "Study template schema", "description": "Study template schema generated by the CEDAR Artifact Library",
   *   "schema:name": "Study", "schema:description": "Study template",
   *   "schema:schemaVersion": "1.6.0", "schema:identifier": "id1212132",
   *   "pav:version": "0.0.1", "bibo:status": "bibo:draft",
   *   "pav:previousVersion": "https://repo.metadatacenter.org/templates/54343",
   *   "pav:derivedFrom": "https://repo.metadatacenter.org/templates/232323",
   *   "@valueType": "https://schema.metadatacenter.org/core/Template",
   *   "@id": "https://repo.metadatacenter.org/templates/474378",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332",
   *   "@context": { ... },
   *   "properties": { ... },
   *   "required": [ "xsd", "pav", "schema", "oslc", "bibo",
   *                 "schema:isBasedOn", "schema:name", "schema:description",
   *                 "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy",
   *                 "Child Name 1", ... "Child Name n"],
   *   "additionalProperties": false,
   *   "_ui": { ... }
   *  }
   * </pre>
   */
  public ObjectNode renderTemplateSchemaArtifact(TemplateSchemaArtifact templateSchemaArtifact)
  {
    ObjectNode rendering = renderSchemaArtifact(templateSchemaArtifact);

    rendering.set(JSON_LD_CONTEXT, renderParentSchemaArtifactContextJsonLdSpecification());

    rendering.put(JSON_SCHEMA_PROPERTIES,
      renderParentSchemaArtifactPropertiesJsonSchemaSpecification(templateSchemaArtifact));

    // TODO Put this list in ModelNodeNames
    rendering.put(JSON_SCHEMA_REQUIRED, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_CONTEXT);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_ID);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_IS_BASED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_ORG_NAME);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_ORG_DESCRIPTION);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_CREATED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_CREATED_BY);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_LAST_UPDATED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(OSLC_MODIFIED_BY);

    for (String childName : templateSchemaArtifact.getChildNames())
      rendering.withArray(JSON_SCHEMA_REQUIRED).add(childName);

    if (templateSchemaArtifact.hasAttributeValueField())
      rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES,
        renderAdditionalPropertiesForAttributeValueFieldJsonSchemaSpecification());
    else
      rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES, false);

    rendering.put(UI, mapper.valueToTree(templateSchemaArtifact.getTemplateUI()));

    return rendering;
  }

  /**
   * Generate a specification for an element schema artifact
   * <p></p>
   * An example artifact specification could look as follows:
   * <pre>
   * {
   *   "$schema": "http://json-schema.org/draft-04/schema#",
   *   "valueType": "object",
   *   "title": "Address element schema", "description: "Address element schema generated by the CEDAR Template Editor 2.6.19",
   *   "schema:name": "Address", "schema:description": "Address element",
   *   "schema:schemaVersion": "1.6.0", "schema:identifier": "id999434",
   *   "pav:version": "0.0.1", "bibo:status": "bibo:draft",
   *   "pav:previousVersion": "https://repo.metadatacenter.org/template-elements/54343",
   *   "pav:derivedFrom": "https://repo.metadatacenter.org/template-elements/232323",
   *   "@valueType": "https://schema.metadatacenter.org/core/TemplateElement",
   *   "@id": "https://repo.metadatacenter.org/templates-elements/474378",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332",
   *   "@context": { ... },
   *   "properties": { ... },
   *   "required": [ "@context", "@id", "Child Name 1", ... "Child Name n"],
   *   "additionalProperties": false,
   *   "_ui": { ... }
   *  }
   * </pre>
   */
  public ObjectNode renderElementSchemaArtifact(ElementSchemaArtifact elementSchemaArtifact)
  {
    ObjectNode rendering = renderSchemaArtifact(elementSchemaArtifact);

    rendering.put(JSON_LD_CONTEXT, renderParentSchemaArtifactContextJsonLdSpecification());

    rendering.put(JSON_SCHEMA_PROPERTIES, renderParentSchemaArtifactPropertiesJsonSchemaSpecification(elementSchemaArtifact));

    // TODO Put this list in ModelNodeNames
    rendering.put(JSON_SCHEMA_REQUIRED, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_CONTEXT);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_ID);

    for (String childName : elementSchemaArtifact.getChildNames())
      rendering.withArray(JSON_SCHEMA_REQUIRED).add(childName);

    if (elementSchemaArtifact.hasAttributeValueField())
      rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES,
        renderAdditionalPropertiesForAttributeValueFieldJsonSchemaSpecification());
    else
      rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES, false);

    rendering.put(UI, mapper.valueToTree(elementSchemaArtifact.getElementUI()));

    // TODO isMultiple, minItem, maxItems

    return rendering;
  }

  /**
   * Generate a specification for a field schema artifact
   * <p></p>
   * An example artifact could look as follows:
   * <pre>
   * {
   *   "$schema": "http://json-schema.org/draft-04/schema#",
   *   "valueType": "object",
   *   "title": "Disease field schema", "description": "Disease field schema generated by the CEDAR Template Editor 2.6.19",
   *   "schema:name": "Disease", "schema:description": "Please enter a disease",
   *   "schema:schemaVersion": "1.6.0", "schema:identifier": "id5666",
   *   "pav:version": "0.0.1", "bibo:status": "bibo:draft",
   *   "pav:previousVersion": "https://repo.metadatacenter.org/templates/435454",
   *   "pav:derivedFrom": "https://repo.metadatacenter.org/templates/893443",
   *   "@valueType": "https://schema.metadatacenter.org/core/Template",
   *   "@id": "https://repo.metadatacenter.org/templates/127666",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332",
   *   "@context": { ... },
   *   "properties": { ... },
   *   "required": [ "@id" ],
   *   "additionalProperties": false,
   *   "skos:prefLabel": "Condition", "skos:altLabel": [ "Problem", "Illness" ],
   *   "_valueConstraints": { ... },
   *   "_ui": { ... }
   *  }
   * </pre>
   */
  public ObjectNode renderFieldSchemaArtifact(FieldSchemaArtifact fieldSchemaArtifact)
  {
    ObjectNode rendering = renderSchemaArtifact(fieldSchemaArtifact);

    rendering.put(JSON_LD_CONTEXT, renderSchemaArtifactContextPrefixesJsonLdSpecification());

    // Static fields have no JSON Schema fields (properties, required, additionalProperties), or
    // value constraints.
    if (!fieldSchemaArtifact.isStatic()) {

      if (fieldSchemaArtifact.hasIRIValue()) {
        rendering.put(JSON_SCHEMA_PROPERTIES, renderIRIFieldArtifactPropertiesJsonSchemaSpecification());
        rendering.put(JSON_SCHEMA_REQUIRED, mapper.createArrayNode());
        rendering.withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_ID);
      } else {
        rendering.put(JSON_SCHEMA_PROPERTIES, renderLiteralFieldArtifactPropertiesJsonSchemaSpecification());
        // Non-IRI fields may have en empty object as a value so there are no required fields
      }

      rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES, false);

      if (fieldSchemaArtifact.getSkosPrefLabel().isPresent())
        rendering.put(SKOS_PREFLABEL, fieldSchemaArtifact.getSkosPrefLabel().get().toString());

      if (!fieldSchemaArtifact.getSkosAlternateLabels().isEmpty()) {
        rendering.put(SKOS_ALTLABEL, mapper.createArrayNode());
        for (String skosAlternateLabel : fieldSchemaArtifact.getSkosAlternateLabels())
          rendering.withArray(SKOS_ALTLABEL).add(skosAlternateLabel.toString());
      }
      rendering.put(VALUE_CONSTRAINTS, mapper.valueToTree(fieldSchemaArtifact.getValueConstraints()));
    }

    rendering.put(UI, mapper.valueToTree(fieldSchemaArtifact.getFieldUI()));

    // TODO isMultiple, minItem, maxItems

    return rendering;
  }

  /**
   * Generate a template instance artifact
   * <p></p>
   * An example template instance artifact could look as follows:
   * <pre>
   *   {
   *   "@context": {
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "schema": "http://schema.org/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "skos": "http://www.w3.org/2004/02/skos/core#",
   *     "schema:name": {"@valueType": "xsd:string" },
   *     "schema:description": { "@valueType": "xsd:string" },
   *     "pav:derivedFrom": { "@valueType": "@id" },
   *     "pav:createdOn": { "@valueType": "xsd:dateTime" },
   *     "pav:createdBy": { "@valueType": "@id" },
   *     "pav:lastUpdatedOn": { "@valueType": "xsd:dateTime" },
   *     "oslc:modifiedBy": { "@valueType": "@id" },
   *     "schema:isBasedOn": { "@valueType": "@id" },
   *     "skos:notation": { "@valueType": "xsd:string" },
   *     "rdfs:label": { "@valueType": "xsd:string" },
   *   },
   *   "@id": "https://repo.metadatacenter.org/template-instances/66776767"
   *   "schema:isBasedOn": "https://repo.metadatacenter.org/templates/5454545",
   *   "schema:name": "Study metadata", "schema:description": "",
   *   "pav:createdOn": "2023-08-01T11:03:05-07:00",
   *   "pav:createdBy": "https://metadatacenter.org/users/344343",
   *   "pav:lastUpdatedOn": "2023-08-01T11:03:05-07:00",
   *   "oslc:modifiedBy": "https://metadatacenter.org/users/5666565"
   * }
   * </pre>
   */
  public ObjectNode renderTemplateInstanceArtifact(TemplateInstanceArtifact templateInstanceArtifact)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_CONTEXT, renderInstanceArtifactContextJsonLdSpecification());

    if (templateInstanceArtifact.getJsonLdId().isPresent())
      rendering.put(JSON_LD_ID, templateInstanceArtifact.getJsonLdId().get().toString());
    else
      rendering.putNull(JSON_LD_ID);

    rendering.put(SCHEMA_IS_BASED_ON, templateInstanceArtifact.getIsBasedOn().toString());
    rendering.put(SCHEMA_ORG_NAME, templateInstanceArtifact.getName());
    rendering.put(SCHEMA_ORG_DESCRIPTION, templateInstanceArtifact.getDescription());

    if (templateInstanceArtifact.getCreatedBy().isPresent())
      rendering.put(PAV_CREATED_BY, templateInstanceArtifact.getCreatedBy().get().toString());
    else
      rendering.putNull(PAV_CREATED_BY);

    if (templateInstanceArtifact.getModifiedBy().isPresent())
      rendering.put(OSLC_MODIFIED_BY, templateInstanceArtifact.getModifiedBy().get().toString());
    else
      rendering.putNull(OSLC_MODIFIED_BY);

    if (templateInstanceArtifact.getCreatedOn().isPresent())
      rendering.put(PAV_CREATED_ON, templateInstanceArtifact.getCreatedOn().get().toString());
    else
      rendering.putNull(PAV_CREATED_BY);
    if (templateInstanceArtifact.getLastUpdatedOn().isPresent())
      rendering.put(PAV_LAST_UPDATED_ON, templateInstanceArtifact.getLastUpdatedOn().get().toString());
    else
      rendering.putNull(PAV_LAST_UPDATED_ON);

    return rendering;
  }
  /**
   * Generate a base schema artifact rendering. In addition to core artifact fields (@valueType, @id, pav:createdOn,
   * pav:createdBy, pav:lastUpdatedOn, and oslc:modifiedBy), it will have JSON Schema fields (@schema, valueType,
   * title, description), Schema.org fields (schema:name, schema:description, schema:schemaVersion,
   * schema:identifier), version fields (pav:version, bibo:status, pav:previousVersion), and a derivation field
   * (pav:derivedFrom).
   * <p></p>
   * An example artifact could look as follows:
   * <pre>
   * {
   *   "$schema": "http://json-schema.org/draft-04/schema#",
   *   "valueType": "object",
   *   "title": "Study template schema", "description": "Bare template schema generated by the CEDAR Template Editor 2.6.19",
   *   "schema:name": "Study", "schema:description": "",
   *   "schema:schemaVersion": "1.6.0", "schema:identifier": "id4343",
   *   "pav:version": "0.0.1", "bibo:status": "bibo:draft",
   *   "pav:previousVersion": "https://repo.metadatacenter.org/templates/435454",
   *   "pav:derivedFrom": "https://repo.metadatacenter.org/templates/893443",
   *   "@valueType": "https://schema.metadatacenter.org/core/Template",
   *   "@id": "https://repo.metadatacenter.org/templates/127666",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332"
   *  }
   * </pre>
   */
  private ObjectNode renderSchemaArtifact(SchemaArtifact schemaArtifact)
  {
    ObjectNode rendering = renderArtifact(schemaArtifact);

    rendering.put(JSON_SCHEMA_SCHEMA, schemaArtifact.getJsonSchemaSchemaUri().toString());
    rendering.put(JSON_SCHEMA_TYPE, JSON_SCHEMA_OBJECT);
    rendering.put(JSON_SCHEMA_TITLE, schemaArtifact.getJsonSchemaTitle());
    rendering.put(JSON_SCHEMA_DESCRIPTION, schemaArtifact.getJsonSchemaDescription());
    rendering.put(SCHEMA_ORG_NAME, schemaArtifact.getName());
    rendering.put(SCHEMA_ORG_DESCRIPTION, schemaArtifact.getDescription());

    rendering.put(SCHEMA_ORG_SCHEMA_VERSION, schemaArtifact.getModelVersion().toString());

    if (schemaArtifact.getIdentifier().isPresent())
      rendering.put(SCHEMA_ORG_IDENTIFIER, schemaArtifact.getIdentifier().get());

    if (schemaArtifact.getVersion().isPresent())
      rendering.put(PAV_VERSION, schemaArtifact.getVersion().get().toString());

    if (schemaArtifact.getStatus().isPresent())
      rendering.put(BIBO_STATUS, schemaArtifact.getStatus().get().toString());

    if (schemaArtifact.getPreviousVersion().isPresent())
      rendering.put(PAV_PREVIOUS_VERSION,
        schemaArtifact.getPreviousVersion().get().toString());

    if (schemaArtifact.getDerivedFrom().isPresent())
      rendering.put(PAV_DERIVED_FROM, schemaArtifact.getDerivedFrom().get().toString());

    return rendering;
  }

  /**
   * Generate an artifact rendering with core fields, which are @valueType, @id, pav:createdOn, pav:createdBy,
   * pav:lastUpdatedOn, and oslc:modifiedBy
   * <p></p>
   * An example artifact could look as follows:
   * <pre>
   * {
   *   "@valueType": "https://schema.metadatacenter.org/core/Template",
   *   "@id": "https://repo.metadatacenter.org/templates/6d21a997-b884-4779-966a-aa71632f3232",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332"
   *  }
   * </pre>
   */
  private ObjectNode renderArtifact(Artifact artifact)
  {
    ObjectNode rendering = renderMonitoredArtifact(artifact);

    if (artifact.getJsonLdTypes().size() == 1) {
      rendering.put(JSON_LD_TYPE, artifact.getJsonLdTypes().get(0).toString());
    } else if (artifact.getJsonLdTypes().size() > 1) {
      rendering.put(JSON_LD_TYPE, mapper.createArrayNode());
      for (URI jsonLdType : artifact.getJsonLdTypes())
        rendering.withArray(JSON_LD_TYPE).add(jsonLdType.toString());
    }

    if (artifact.getJsonLdId().isPresent())
      rendering.put(JSON_LD_ID, artifact.getJsonLdId().get().toString());

    return rendering;
  }

  /**
   * Generate a monitored artifact rendering, which will have fields pav:createdOn, pav:createdBy, pav:lastUpdatedOn,
   * and oslc:modifiedBy
   * <p></p>
   * An example could look as follows:
   * <pre>
   * {
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332"
   *  }
   * </pre>
   */
  private ObjectNode renderMonitoredArtifact(MonitoredArtifact monitoredArtifact)
  {
    ObjectNode rendering = mapper.createObjectNode();

    if (monitoredArtifact.getCreatedBy().isPresent())
      rendering.put(PAV_CREATED_BY, monitoredArtifact.getCreatedBy().get().toString());

    if (monitoredArtifact.getModifiedBy().isPresent())
      rendering.put(OSLC_MODIFIED_BY, monitoredArtifact.getModifiedBy().get().toString());

    if (monitoredArtifact.getCreatedOn().isPresent())
      rendering.put(PAV_CREATED_ON, monitoredArtifact.getCreatedOn().get().toString());

    if (monitoredArtifact.getLastUpdatedOn().isPresent())
      rendering.put(PAV_LAST_UPDATED_ON, monitoredArtifact.getLastUpdatedOn().get().toString());

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for an additionalProperties field for a template or element containing
   * an attribute-value field
   * <p>
   * The specification is defined as follows:
   * <pre>
   * {
   *   "valueType": "object",
   *   "properties": {
   *     "@value": { "valueType": [ "string", "null" ] },
   *     "@valueType": { "valueType": "string", "format": "uri" }
   *   },
   *   "required": [ "@value" ],
   *   "additionalProperties": false
   * }
   * </pre>
   * The additional properties are of valueType object and contain two main properties:
   * - "@value": A string or null value.
   * - "@valueType": A string representing a URI.
   * <p>
   * The "@value" property is required, while the "@valueType" property is optional.
   * The "@value" property can hold a string value or be null, while the "@valueType" property must be a string in URI format.
   * <p>
   * Note that no other additional properties are allowed due to "additionalProperties" being set to false.
   */
  private ObjectNode renderAdditionalPropertiesForAttributeValueFieldJsonSchemaSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, JSON_SCHEMA_OBJECT);
    rendering.put(JSON_SCHEMA_PROPERTIES, mapper.createObjectNode());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(JSON_LD_VALUE, renderStringOrNullJsonSchemaTypeSpecification());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(JSON_LD_TYPE, renderUriJsonSchemaTypeSpecification());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(JSON_SCHEMA_REQUIRED, mapper.createArrayNode());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).withArray(JSON_SCHEMA_REQUIRED).add(JSON_LD_VALUE);
    rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES, false);

    return rendering;
  }

  /**
   * Render a JSON Schema properties specification in a parent schema artifact. This specification defines
   * the JSON-LD @context field in a parent artifact. In addition to standard prefixes (e.g., rdfs, xsd) and
   * fields (schema:name, pav:createdOn) the @context also contains property IRI mappings for every child field.
   * <p></p>
   * Defined as follows:
   * <pre>
   *   {
   *     "@context": {
   *       "valueType": "object",
   *       "properties": {
   *         "rdfs": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2000/01/rdf-schema#"] },
   *         "xsd": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2001/XMLSchema#"] },
   *         "pav": { "valueType": "string", "format": "uri", "enum": ["http://purl.org/pav/"] },
   *         "schema": { "valueType": "string", "format": "uri", "enum": ["http://schema.org/"] },
   *         "oslc": { "valueType": "string", "format": "uri", "enum": ["http://open-services.net/ns/core#"] },
   *         "skos": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2004/02/skos/core#"] },
   *         "rdfs:label": { "valueType": "object", "properties": { "@valueType": { "valueType": "string", "enum": ["xsd:string"] }}},
   *         "schema:isBasedOn": { "valueType": "object", "properties": {"@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "schema:name": { "valueType": "object", "properties": {"@valueType": { "valueType": "string",  "enum": ["xsd:string"] }}},
   *         "schema:description": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:string"] }}},
   *         "pav:derivedFrom": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "pav:createdOn": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:dateTime"] }}},
   *         "pav:createdBy": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "pav:lastUpdatedOn": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:dateTime"] }}},
   *         "oslc:modifiedBy": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }} },
   *         "[Child Name 1]": { "enum": [ "[CHILD_PROPERTY_URI_1]"] },
   *         ...
   *         "[Child Name n]": { "enum": [ "[CHILD_PROPERTY_URI_n]"] }
   *       },
   *       "required": [ "xsd", "pav", "schema", "oslc", "schema:isBasedOn", "schema:name", "schema:description",
   *                     "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy",
   *                     "[Child Name 1]", ... "[Child Name n]" ],
   *       "additionalProperties": false
   *     },
   *     "@id": { "valueType": [ "string", "null" ], "format": "uri" },
   *     "@valueType": { "oneOf": [ { "valueType": "string","format": "uri" },
   *                           { "valueType": "array", "minItems": 1, 'items": { "valueType": "string","format": "uri" }, "uniqueItems": true } ]
   *              },
   *     "schema:isBasedOn": { "valueType": "string", "format": "uri" },
   *     "schema:name": { "valueType": "string","minLength": 1 },
   *     "schema:description": { "valueType": "string" },
   *     "pav:derivedFrom": { "valueType": "string", "format": "uri" },
   *     "pav:createdOn": { "valueType": [ "string", "null" ], "format": "date-time" },
   *     "pav:createdBy": { "valueType": [ "string", "null" ], "format": "uri" },
   *     "pav:lastUpdatedOn": {  "valueType": [ "string", "null" ], "format": "date-time" },
   *     "oslc:modifiedBy": { "valueType": [ "string", "null" ], "format": "uri" }
   *     "[Child Name 1]": { [Child JSON Schema 1] },
   *     ...
   *     "[Child Name n]": { [Child JSON Schema n] }
   *   }
   * </pre>
   * A conforming instance should look as follows:
   * <pre>
   * {
   *   "@context": {
   *     "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
   *     "pav": "http://purl.org/pav/",
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "schema": "https://schema.org/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "skos": "http://www.w3.org/2004/02/skos/core#",
   *     "rdfs:label": { "@valueType": "xsd:string" },
   *     "schema:isBasedOn": { "@valueType": "@id" },
   *     "schema:name": { "@valueType": "xsd:string" },
   *     "schema:description": { "@valueType": "xsd:string" },
   *     "pav:derivedFrom": { "@valueType": "@id" },
   *     "pav:createdOn": {  "@valueType": "xsd:dateTime" },
   *     "pav:createdBy": { "@valueType": "@id" },
   *     "oslc:modifiedBy": { "@valueType": "@id" },
   *     "Child Name 1": "https://myschema.org/property/p1"
   *     ...
   *     "Child Name n": "https://myschema.org/property/pn"
   *   },
   *   "@valueType": "https://www.example.com/Study",
   *   "@id": "https://repo.metadatacenter.org/template-instances/474378",
   *   "schema:isBasedOn": "",
   *   "schema:name": "Study SDY232", "schema:description": "Metadata for SDY232 study",
   *   "pav:createdOn": "2023-07-28T11:10:41-07:00", "pav:createdBy": "https://metadatacenter.org/users/656433",
   *   "pav:lastUpdatedOn": "2023-07-28T11:10:41-07:00", "oslc:modifiedBy": "https://metadatacenter.org/users/524332",
   *   "Child Name 1": { [Child JSON-LD 1] },
   *   ...
   *   "Child Name n": { [Child JSON-LD n] }
   * }
   * </pre>
   */
  private ObjectNode renderParentSchemaArtifactPropertiesJsonSchemaSpecification(ParentSchemaArtifact parentSchemaArtifact)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_CONTEXT, renderParentSchemaArtifactContextPropertiesJsonSchemaSpecification(parentSchemaArtifact));
    rendering.put(JSON_LD_TYPE, renderUriOrUriArrayJsonSchemaSpecification(1, true));
    rendering.put(JSON_LD_ID, renderUriOrNullJsonSchemaTypeSpecification());
    rendering.put(SCHEMA_IS_BASED_ON, renderUriJsonSchemaTypeSpecification());
    rendering.put(SCHEMA_ORG_NAME, renderStringJsonSchemaTypeSpecification(1));
    rendering.put(SCHEMA_ORG_DESCRIPTION, renderStringJsonSchemaTypeSpecification(0));
    rendering.put(PAV_DERIVED_FROM, renderUriJsonSchemaTypeSpecification());
    rendering.put(PAV_CREATED_ON, renderDateTimeOrNullJsonSchemaTypeSpecification());
    rendering.put(PAV_CREATED_BY, renderUriOrNullJsonSchemaTypeSpecification());
    rendering.put(PAV_LAST_UPDATED_ON, renderDateTimeOrNullJsonSchemaTypeSpecification());
    rendering.put(OSLC_MODIFIED_BY, renderUriOrNullJsonSchemaTypeSpecification());

    for (ChildSchemaArtifact childSchemaArtifact : parentSchemaArtifact.getChildSchemas()) {
      // TODO Add child schema
    }

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for a @context properties specification in a parent artifact
   * <p></p>
   * Defined as follows:
   * <pre>
   *   {
   *     "properties": {
   *         "rdfs": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2000/01/rdf-schema#"] },
   *         "xsd": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2001/XMLSchema#"] },
   *         "pav": { "valueType": "string", "format": "uri", "enum": ["http://purl.org/pav/"] },
   *         "schema": { "valueType": "string", "format": "uri", "enum": ["http://schema.org/"] },
   *         "oslc": { "valueType": "string", "format": "uri", "enum": ["http://open-services.net/ns/core#"] },
   *         "skos": { "valueType": "string", "format": "uri", "enum": ["http://www.w3.org/2004/02/skos/core#"] },
   *         "rdfs:label": { "valueType": "object", "properties": { "@valueType": { "valueType": "string", "enum": ["xsd:string"] }}},
   *         "schema:isBasedOn": { "valueType": "object", "properties": {"@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "schema:name": { "valueType": "object", "properties": {"@valueType": { "valueType": "string",  "enum": ["xsd:string"] }}},
   *         "schema:description": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:string"] }}},
   *         "pav:derivedFrom": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "pav:createdOn": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:dateTime"] }}},
   *         "pav:createdBy": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }}},
   *         "pav:lastUpdatedOn": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["xsd:dateTime"] }}},
   *         "oslc:modifiedBy": { "valueType": "object", "properties": { "@valueType": {  "valueType": "string",  "enum": ["@id"] }} },
   *         "<Child Name 1>": { "enum": [ "<PROPERTY_URI_1>"] },
   *         ...
   *         "<Child Name n>": { "enum": [ "<PROPERTY_URI_n>"] }
   *     }
   *   }
   * </pre>
   * A conforming instance should look as follows:
   * <pre>
   *   {
   *     "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "schema": "https://schema.org/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "skos": "http://www.w3.org/2004/02/skos/core#",
   *     "rdfs:label": { "@valueType": "xsd:string" },
   *     "schema:isBasedOn": { "@valueType": "@id" },
   *     "schema:name": { "@valueType": "xsd:string" },
   *     "schema:description": { "@valueType": "xsd:string" },
   *     "pav:derivedFrom": { "@valueType": "@id" },
   *     "pav:createdOn": {  "@valueType": "xsd:dateTime" },
   *     "pav:createdBy": { "@valueType": "@id" },
   *     "oslc:modifiedBy": { "@valueType": "@id" },
   *     "Child Name 1": "https://myschema.org/property/p1"
   *     ...
   *     "Child Name n": "https://myschema.org/property/pn"
   *   }
   * </pre>
   */
  private ObjectNode renderParentSchemaArtifactContextPropertiesJsonSchemaSpecification(ParentSchemaArtifact parentSchemaArtifact)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_PROPERTIES, mapper.createObjectNode());

    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(RDFS, renderJsonSchemaUriEnumSpecification(RDFS_IRI));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(XSD, renderJsonSchemaUriEnumSpecification(XSD_IRI));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(PAV, renderJsonSchemaUriEnumSpecification(PAV_IRI));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(SCHEMA, renderJsonSchemaUriEnumSpecification(SCHEMA_IRI));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(OSLC, renderJsonSchemaUriEnumSpecification(OSLC_IRI));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(SKOS, renderJsonSchemaUriEnumSpecification(SKOS_IRI));

    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(ModelNodeNames.RDFS_LABEL, renderJsonSchemaJsonLdDatatypeSpecification("xsd:string"));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(SCHEMA_IS_BASED_ON, renderJsonSchemaJsonLdDatatypeSpecification(
      JSON_LD_ID));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(SCHEMA_ORG_NAME, renderJsonSchemaJsonLdDatatypeSpecification("xsd:string"));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(SCHEMA_ORG_DESCRIPTION, renderJsonSchemaJsonLdDatatypeSpecification("xsd:string"));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(PAV_DERIVED_FROM, renderJsonSchemaJsonLdDatatypeSpecification(
      JSON_LD_ID));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(PAV_CREATED_ON, renderJsonSchemaJsonLdDatatypeSpecification("xsd:dateTime"));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(PAV_CREATED_BY, renderJsonSchemaJsonLdDatatypeSpecification(
      JSON_LD_ID));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(PAV_LAST_UPDATED_ON, renderJsonSchemaJsonLdDatatypeSpecification("xsd:dateTime"));
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(OSLC_MODIFIED_BY, renderJsonSchemaJsonLdDatatypeSpecification(
      JSON_LD_ID));

    for (Map.Entry<String, URI> entry : parentSchemaArtifact.getChildPropertyURIs().entrySet()) {
      String childName = entry.getKey();
      URI propertyURI = entry.getValue();
      rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(childName, propertyURI.toString());
    }

    rendering.put(JSON_SCHEMA_REQUIRED, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(XSD);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(OSLC);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_IS_BASED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_ORG_NAME);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(SCHEMA_ORG_DESCRIPTION);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_CREATED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_CREATED_BY);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(PAV_LAST_UPDATED_ON);
    rendering.withArray(JSON_SCHEMA_REQUIRED).add(OSLC_MODIFIED_BY);

    // TODO Check that all children have an IRI mapping
    for (String childName : parentSchemaArtifact.getChildPropertyURIs().keySet())
      rendering.withArray(JSON_SCHEMA_REQUIRED).add(childName);

    rendering.put(JSON_SCHEMA_ADDITIONAL_PROPERTIES, false);

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for a URI-formatted string value with a specific value.
   * <p></p>
   * Defined as follows:
   * <pre>
   * { "valueType": "string", "format": "uri", "enum": ["<IRI>"] }
   * </pre>
   * A conforming value could look as follows:
   * <pre>
   *   "http://purl.org/pav/"
   * </pre>
   */
  private ObjectNode renderJsonSchemaUriEnumSpecification(String uri)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, "string");
    rendering.put(ModelNodeNames.JSON_SCHEMA_FORMAT, "uri");
    rendering.put(ModelNodeNames.JSON_SCHEMA_ENUM, mapper.createArrayNode());
    rendering.withArray(ModelNodeNames.JSON_SCHEMA_ENUM).add(uri);

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for a JSON-LD @valueType datatype specification
   * <p></p>
   * Defined as follows:
   * <pre>
   * { "valueType": "object", "properties": { "@valueType": { "valueType": "string", "enum": ["<DATATYPE>"] }}},
   * </pre>
   * A conforming value could look as follows:
   * <pre>
   *   { "@valueType": "xsd:string" }
   * </pre>
   */
  private ObjectNode renderJsonSchemaJsonLdDatatypeSpecification(String datatype)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, JSON_SCHEMA_OBJECT);
    rendering.put(JSON_SCHEMA_PROPERTIES, mapper.createObjectNode());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES).put(JSON_LD_TYPE, mapper.createObjectNode());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES)
      .withObject("/" + JSON_LD_TYPE).put(JSON_SCHEMA_TYPE, "string");
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES)
      .withObject("/" + JSON_LD_TYPE).put(ModelNodeNames.JSON_SCHEMA_ENUM, mapper.createArrayNode());
    rendering.withObject("/" + JSON_SCHEMA_PROPERTIES)
      .withObject( "/" + JSON_LD_TYPE).withArray(ModelNodeNames.JSON_SCHEMA_ENUM).add(datatype);

    return rendering;
  }

  /**
   * Generate a JSON-LD @context for parent schema artifacts (i.e., templates and elements)
   * <p>
   * Defined as follows:
   * <pre>
   *   {
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "bibo": "http://purl.org/ontology/bibo/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "schema": "http://schema.org/",
   *     "schema:name": { "@valueType": "xsd:string" },
   *     "schema:description": { "@valueType": "xsd:string" },
   *     "pav:createdOn": { "@valueType": "xsd:dateTime" },
   *     "pav:createdBy": { "@valueType": "@id" },
   *     "pav:lastUpdatedOn": { "@valueType": "xsd:dateTime" },
   *     "oslc:modifiedBy": { "@valueType": "@id" }
   *   }
   * </pre>
   */
  private ObjectNode renderParentSchemaArtifactContextJsonLdSpecification()
  {
    ObjectNode rendering = renderSchemaArtifactContextPrefixesJsonLdSpecification();

    rendering.put(SCHEMA_ORG_NAME, renderXsdStringJsonLdSpecification());
    rendering.put(SCHEMA_ORG_DESCRIPTION, renderXsdStringJsonLdSpecification());
    rendering.put(PAV_CREATED_ON, renderXsdDateTimeJsonLdSpecification());
    rendering.put(PAV_CREATED_BY, renderIriJsonLdSpecification());
    rendering.put(PAV_LAST_UPDATED_ON, renderXsdDateTimeJsonLdSpecification());
    rendering.put(OSLC_MODIFIED_BY, renderIriJsonLdSpecification());

    return rendering;
  }

  /**
   * Generate a JSON-LD @context for instance artifacts
   * <p>
   * Defined as follows:
   * <pre>
   *   {
   *     "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "schema": "http://schema.org/",
   *     "skos": "http://www.w3.org/2004/02/skos/core#",
   *     "schema:name": { "@valueType": "xsd:string" },
   *     "schema:description": { "@valueType": "xsd:string" },
   *     "pav:createdOn": { "@valueType": "xsd:dateTime" },
   *     "pav:createdBy": { "@valueType": "@id" },
   *     "pav:lastUpdatedOn": { "@valueType": "xsd:dateTime" },
   *     "oslc:modifiedBy": { "@valueType": "@id" },
   *     "rdfs:label": { "@valueType": "xsd:string" },
   *     "skos:notation": { "@valueType": "xsd:string" }
   *     "schema:isBasedOn": { "@valueType": "@id" }
   *   }
   * </pre>
   */
  private ObjectNode renderInstanceArtifactContextJsonLdSpecification()
  {
    ObjectNode rendering = renderInstanceArtifactContextPrefixesJsonLdSpecification();

    rendering.put(SCHEMA_ORG_NAME, renderXsdStringJsonLdSpecification());
    rendering.put(SCHEMA_ORG_DESCRIPTION, renderXsdStringJsonLdSpecification());
    rendering.put(PAV_CREATED_ON, renderXsdDateTimeJsonLdSpecification());
    rendering.put(PAV_CREATED_BY, renderIriJsonLdSpecification());
    rendering.put(PAV_LAST_UPDATED_ON, renderXsdDateTimeJsonLdSpecification());
    rendering.put(OSLC_MODIFIED_BY, renderIriJsonLdSpecification());

    return rendering;
  }

  /**
   * Generate JSON-LD @context prefix specification for schema artifacts
   * <p></p>
   * Defined as follows:
   * <pre>
   *   "@context": {
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "bibo": "http://purl.org/ontology/bibo/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "schema": "http://schema.org/"
   *   }
   * </pre>
   */
  private ObjectNode renderSchemaArtifactContextPrefixesJsonLdSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(XSD, XSD_IRI);
    rendering.put(PAV, PAV_IRI);
    rendering.put(OSLC, OSLC_IRI);
    rendering.put(SCHEMA, SCHEMA_IRI);
    rendering.put(BIBO, BIBO_IRI);

    return rendering;
  }

  /**
   * Generate JSON-LD @context prefix specification for instance artifacts
   * <p></p>
   * Defined as follows:
   * <pre>
   *   "@context": {
   *     "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
   *     "xsd": "http://www.w3.org/2001/XMLSchema#",
   *     "pav": "http://purl.org/pav/",
   *     "oslc": "http://open-services.net/ns/core#",
   *     "schema": "http://schema.org/",
   *     "skos": "http://www.w3.org/2004/02/skos/core#"
   *   }
   * </pre>
   */
  private ObjectNode renderInstanceArtifactContextPrefixesJsonLdSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(RDFS, RDFS_IRI);
    rendering.put(XSD, XSD_IRI);
    rendering.put(PAV, PAV_IRI);
    rendering.put(OSLC, OSLC_IRI);
    rendering.put(SCHEMA, SCHEMA_IRI);
    rendering.put(SKOS, SKOS_IRI);

    return rendering;
  }

  /**
   * Generate a JSON Schema properties specification for a literal-valued field
   * <p></p>
   * Defined as follows:
   * <pre>
   * {
   *   "@valueType": {
   *     "oneOf": [
   *       { "valueType": "string", "format": "uri" },
   *       { "valueType": "array", "minItems": 1, "items": { "valueType": "string", "format": "uri" },  "uniqueItems": true }
   *     ]
   *   },
   *   "rdfs:label": {  "valueType": [ "string", "null" ] },
   *   "@value": {  "valueType": [ "string", "null" ] }
   * }
   * </pre>
   * A conforming value could look like:
   * <pre>
   * {
   *   "@valueType": "http://www.w3.org/2001/XMLSchema#string",
   *   "@value": "Bob"
   * }
   * </pre>
   */
  private ObjectNode renderLiteralFieldArtifactPropertiesJsonSchemaSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_TYPE, renderUriOrUriArrayJsonSchemaSpecification(1, true));
    rendering.put(ModelNodeNames.RDFS_LABEL, renderStringOrNullJsonSchemaTypeSpecification());
    rendering.put(JSON_LD_VALUE, renderStringOrNullJsonSchemaTypeSpecification());

    return rendering;
  }


  /**
   * Generate a JSON Schema properties specification for a IRI-valued field
   * <p>
   * Defined as follows:
   * <pre>
   * {
   *   "@valueType": {
   *     "oneOf": [
   *       { "valueType": "string", "format": "uri" },
   *       { "valueType": "array", "minItems": 1, "items": { "valueType": "string", "format": "uri" },  "uniqueItems": true }
   *     ]
   *   },
   *   "rdfs:label": {  "valueType": [ "string", "null" ] },
   *   "@id": { "valueType": "string", "format": "uri" }
   * }
   * </pre>
   * A conforming value could look like:
   * <pre>
   * {
   *   "rsfs:label": "Melanoma",
   *   "@id": "http://purl.bioontology.org/ontology/LNC/LA14279-6"
   * }
   * </pre>
   */
  private ObjectNode renderIRIFieldArtifactPropertiesJsonSchemaSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_TYPE, renderUriOrUriArrayJsonSchemaSpecification(1, true));
    rendering.put(ModelNodeNames.RDFS_LABEL, renderStringOrNullJsonSchemaTypeSpecification());
    rendering.put(JSON_LD_ID, renderUriJsonSchemaTypeSpecification());

    return rendering;
  }

  /**
   * Generate a JSON Schema valueType specification for a string value
   * <p>
   * Defined as follows:
   * <pre>
   *   { "valueType": "string", "minLength": [minLength] }
   * </pre>
   */
  private ObjectNode renderStringJsonSchemaTypeSpecification(int minLength)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, "string");

    if (minLength > 0)
     rendering.put(JSON_SCHEMA_MIN_LENGTH, minLength);

    return rendering;
  }

  /**
   * Generate a JSON Schema valueType specification for a string or null value
   * <p>
   * Defined as follows:
   * <pre>
   *   { "valueType": [ "string", "null" ] }
   * </pre>
   */
  private ObjectNode renderStringOrNullJsonSchemaTypeSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_TYPE).add("string");
    rendering.withArray(JSON_SCHEMA_TYPE).add("null");

    return rendering;
  }

  /**
   * Generate a JSON Schema valueType specification for a URI-formatted string or null value
   * <p>
   * Defined as follows:
   * <pre>
   //   { "valueType": [ "string", "null" ], "format": "uri" },
   * </pre>
   */
  private ObjectNode renderUriOrNullJsonSchemaTypeSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_TYPE).add("string");
    rendering.withArray(JSON_SCHEMA_TYPE).add("null");

    rendering.put(JSON_SCHEMA_FORMAT, "uri");

    return rendering;
  }

  /**
   * Generate a JSON-LD @valueType specification for an xsd:string
   * <p>
   * Defined as follows:
   * <pre>
   *   { "@valueType": "xsd:string" }
   * </pre>
   */
  private ObjectNode renderXsdStringJsonLdSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_TYPE, "xsd:string");

    return rendering;
  }

  /**
   * Generate a JSON-LD @valueType specification for an xsd:dateTime
   * <p>
   * Defined as follows:
   * <pre>
   *   { "@valueType": "xsd:dateTime" }
   * </pre>
   */
  private ObjectNode renderXsdDateTimeJsonLdSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_TYPE, "xsd:dateTime");

    return rendering;
  }

  /**
   * Generate a JSON-LD @valueType specification for an IRI
   * <p>
   * Defined as follows:
   * <pre>
   *   { "@valueType": "@id" }
   * </pre>
   */
  private ObjectNode renderIriJsonLdSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_LD_TYPE, JSON_LD_ID);

    return rendering;
  }

  /**
   * Generate a JSON Schema valueType specification for a date-time or null value
   * <p>
   * Defined as follows:
   * <pre>
   *  { "valueType": [ "string", "null" ], "format": "date-time" },
   * </pre>
   */
  private ObjectNode renderDateTimeOrNullJsonSchemaTypeSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, mapper.createArrayNode());
    rendering.withArray(JSON_SCHEMA_TYPE).add("string");
    rendering.withArray(JSON_SCHEMA_TYPE).add("null");
    rendering.put(JSON_SCHEMA_FORMAT, "date-time");

    return rendering;
  }


  /**
   * Generate a JSON Schema specification for a URI-formatted string
   * <p>
   * Defined as follows:
   * <pre>
   *   { "valueType": "string", "format": "uri" }
   * </pre>
   */
  private ObjectNode renderUriJsonSchemaTypeSpecification()
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, "string");
    rendering.put(ModelNodeNames.JSON_SCHEMA_FORMAT, "uri");

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for URI-formatted string or URI-formatted string array
   * <p>
   * Defined as follows:
   * <pre>
   * {
   *   "oneOf": [
   *     { "valueType": "string", "format": "uri" },
   *     { "valueType": "array", "minItems": 1, "items": { "valueType": "string", "format": "uri" }, "uniqueItems": true }
   *   ]
   * }
   * </pre>
   */
  private ObjectNode renderUriOrUriArrayJsonSchemaSpecification(int minItems, boolean uniqueItems)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(ModelNodeNames.JSON_SCHEMA_ONE_OF, mapper.createArrayNode());
    rendering.withArray(ModelNodeNames.JSON_SCHEMA_ONE_OF).add(renderUriJsonSchemaTypeSpecification());
    rendering.withArray(ModelNodeNames.JSON_SCHEMA_ONE_OF).add(renderUriArrayJsonSchemaTypeSpecification(1, true));

    return rendering;
  }

  /**
   * Generate a JSON Schema specification for URI-formatted string array
   * <p>
   * Defined as follows:
   * <pre>
   * { "valueType": "array", "minItems": [minItems], "items": { "valueType": "string", "format": "uri" }, "uniqueItems": [uniqueItems] }
   * </pre>
   */
  private ObjectNode renderUriArrayJsonSchemaTypeSpecification(int minItems, boolean uniqueItems)
  {
    ObjectNode rendering = mapper.createObjectNode();

    rendering.put(JSON_SCHEMA_TYPE, ModelNodeNames.JSON_SCHEMA_ARRAY);
    rendering.put(ModelNodeNames.JSON_SCHEMA_MIN_ITEMS, minItems);
    rendering.put(ModelNodeNames.JSON_SCHEMA_ITEMS, mapper.createObjectNode());
    rendering.withObject( "/" + ModelNodeNames.JSON_SCHEMA_ITEMS).put(JSON_SCHEMA_TYPE, "string");
    rendering.withObject( "/" + ModelNodeNames.JSON_SCHEMA_ITEMS).put(ModelNodeNames.JSON_SCHEMA_FORMAT, "uri");
    rendering.put(ModelNodeNames.JSON_SCHEMA_UNIQUE_ITEMS, uniqueItems);

    return rendering;
  }
}
